name: Build and Deploy

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-env: production
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies 🔧
        run: npm install --legacy-peer-deps

      - name: Build 🏗️
        run: npm run build
        env:
          CI: false # Prevents warnings from being treated as errors during build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
